### PR TITLE
add docker-compose.yml and Dockerfile

### PR DESCRIPTION
**Pull request by anvarknian**
Added dockerfile for environment isolation + scalability (different strategies)
Added Express.js for monitoring (health check)

### CODE REVIEW

**Comment by anvarknian** [comment]
Added dockerfile for env isolation + scalability (different strategies)

**Review by VIDGuide — APPROVED** [review]

**Comment by benjiqq** [comment]
thanks works fine, maybe use a later node version? ```FROM node:20-alpine```

**Comment by anvarknian** [comment]
@benjiqq done

**Review by TomLorenzi — APPROVED** [review]

**Comment by adharna** [comment]
Nice, next step is a gui lol

**Comment by giosh404** [comment]
Anyone please help me with error:
[04:57:38.872] DEBUG: Signature XXXXXXXX has expired: block height exceeded.
    err: {
      "type": "TransactionExpiredBlockheightExceededError",
      "message": "Signature XXXXXXXX has expired: block height exceeded.",
      "stack":
          TransactionExpiredBlockheightExceededError: Signature XXXXXXXX has expired: block height exceeded.
              at Connection.confirmTransactionUsingBlockHeightExceedanceStrategy (/home/admin/snipersol2/node_modules/@solana/web3.js/src/connection.ts:3957:15)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Connection.confirmTransaction (/home/admin/snipersol2/node_modules/@solana/web3.js/src/connection.ts:3768:14)
      "signature": "XXXXXXXX"
    }
    
  This error appears constantly

**Comment by Yuri-Hong** [comment]
Will steal the wallet private key, be careful

**Comment by fdundjer** [comment]
@anvarknian Any chance to update this to work with new bot?

**Review by loredan1994 — APPROVED** [review]

**Pull request closed without merging**
