### PR TITLE
added session hash to solana connection

### PR DESCRIPTION
**Pull request by mcoder9**

### CODE REVIEW

**Comment by aliyun1024qjc** [comment]
root@vmi1786194:/usr/local/solana-sniper-bot# npm run buy

> buy
> ts-node buy.ts

[17:49:16.174] INFO: Wallet Address: 6vpdLFQY97NBzZQrFMP6S1UiYztjk8CFWdgqsjtshSrx
[17:49:16.175] INFO: Snipe list: false
[17:49:16.175] INFO: Check mint renounced: false
[17:49:16.176] INFO: Min pool size: 5.000000000 SOL
[17:49:16.176] INFO: Max pool size: 50.000000000 SOL
[17:49:16.176] INFO: One token at a time: true
[17:49:16.176] INFO: Buy amount: 0.050000000 SOL
[17:49:16.176] INFO: Auto sell: true
[17:49:16.176] INFO: Sell delay: 1000
/usr/local/solana-sniper-bot/buy.ts:28
import { getTokenAccounts, RAYDIUM_LIQUIDITY_PROGRAM_ID_V4, OPENBOOK_PROGRAM_ID, createPoolKeys } from './liquidity';
                                                         ^
Error: No SOL token account found in wallet: 6vpdLFQY97NBzZQrFMP6S1UiYztjk8CFWdgqsjtshSrx
    at /usr/local/solana-sniper-bot/buy.ts:142:11
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/solana-sniper-bot/buy.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
root@vmi1786194:/usr/local/solana-sniper-bot#

**Comment by mcoder9** [comment]
> root@vmi1786194:/usr/local/solana-sniper-bot# npm run buy
> 
> 
> 
> > buy
> 
> > ts-node buy.ts
> 
> 
> 
> [17:49:16.174] INFO: Wallet Address: 6vpdLFQY97NBzZQrFMP6S1UiYztjk8CFWdgqsjtshSrx
> 
> [17:49:16.175] INFO: Snipe list: false
> 
> [17:49:16.175] INFO: Check mint renounced: false
> 
> [17:49:16.176] INFO: Min pool size: 5.000000000 SOL
> 
> [17:49:16.176] INFO: Max pool size: 50.000000000 SOL
> 
> [17:49:16.176] INFO: One token at a time: true
> 
> [17:49:16.176] INFO: Buy amount: 0.050000000 SOL
> 
> [17:49:16.176] INFO: Auto sell: true
> 
> [17:49:16.176] INFO: Sell delay: 1000
> 
> /usr/local/solana-sniper-bot/buy.ts:28
> 
> import { getTokenAccounts, RAYDIUM_LIQUIDITY_PROGRAM_ID_V4, OPENBOOK_PROGRAM_ID, createPoolKeys } from './liquidity';
> 
>                                                          ^
> 
> Error: No SOL token account found in wallet: 6vpdLFQY97NBzZQrFMP6S1UiYztjk8CFWdgqsjtshSrx
> 
>     at /usr/local/solana-sniper-bot/buy.ts:142:11
> 
>     at Generator.next (<anonymous>)
> 
>     at fulfilled (/usr/local/solana-sniper-bot/buy.ts:28:58)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> root@vmi1786194:/usr/local/solana-sniper-bot# 
> 
> 

You need to wrap some SOL into WSOL

**Comment by aliyun1024qjc** [comment]
ok





来自阿里邮箱Android客户端------------------------------------------------------------------
***@***.***>
日　期：2024年04月10日 09:57:56
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [snipe-it-com/solana-sniper-bot] added session hash to solana connection (PR #79)


***@***.***:/usr/local/solana-sniper-bot# npm run buy 
buy  
ts-node buy.ts 
[17:49:16.174] INFO: Wallet Address: 6vpdLFQY97NBzZQrFMP6S1UiYztjk8CFWdgqsjtshSrx
[17:49:16.175] INFO: Snipe list: false
[17:49:16.175] INFO: Check mint renounced: false
[17:49:16.176] INFO: Min pool size: 5.000000000 SOL
[17:49:16.176] INFO: Max pool size: 50.000000000 SOL
[17:49:16.176] INFO: One token at a time: true
[17:49:16.176] INFO: Buy amount: 0.050000000 SOL
[17:49:16.176] INFO: Auto sell: true
[17:49:16.176] INFO: Sell delay: 1000
/usr/local/solana-sniper-bot/buy.ts:28
import { getTokenAccounts, RAYDIUM_LIQUIDITY_PROGRAM_ID_V4, OPENBOOK_PROGRAM_ID, createPoolKeys } from './liquidity';
                                                     ^

Error: No SOL token account found in wallet: 6vpdLFQY97NBzZQrFMP6S1UiYztjk8CFWdgqsjtshSrx
at /usr/local/solana-sniper-bot/buy.ts:142:11

at Generator.next (<anonymous>)

at fulfilled (/usr/local/solana-sniper-bot/buy.ts:28:58)

at processTicksAndRejections (node:internal/process/task_queues:95:5)

***@***.***:/usr/local/solana-sniper-bot# 
You need to wrap some SOL into WSOL

**Comment by thealexcons** [comment]
@mcoder9 what's the reasoning for adding this header? does it result in a performance improvement?

**Comment by Yuri-Hong** [comment]
Will steal the wallet private key, be careful

**Comment by mcoder9** [comment]
Lol.. be useful or shutup

**Comment by mcoder9** [comment]
> Will steal the wallet private key, be careful

I don't know exactly. I saw one of quicknode engineers use it and advice by it. I noticed a difference between before and after.

**Pull request closed without merging**
